import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@/app/styles/globals.scss";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import "react-draft-wysiwyg/dist/react-draft-wysiwyg.css";
import { AuthProvider } from "@/context/AuthContext";
import AuthGuard from "@/components/AuthGuard";
import NextProgressBar from "@/components/NextProgressBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextProgressBar />
        <AuthProvider>
          <AuthGuard>
            <>
              {children}
              <ToastContainer />
            </>
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
